const SCHEDULECOMMAND = "schedule";
const VIEWSCHEDULEDCOMMAND = "viewscheduled";
const SCHEDULEMESSAGEACTION = "Schedule Message";
const SCHEDULEFORMHANDLER = "msgSchFormHandler";
const UTILITYBUTTONHANDLER = "msgSchUtility";

module.exports = {
  SCHEDULECOMMAND,
  VIEWSCHEDULEDCOMMAND,
  SCHEDULEMESSAGEACTION,
  SCHEDULEFORMHANDLER,
  UTILITYBUTTONHANDLER,
};
