const SCHEDULECOMMAND = "schedule";
const VIEWSCHEDULEDCOMMAND = "viewscheduled";
const SCHEDULEMESSAGEACTION = "Schedule Message";
const SCHEDULEFORMHANDLER = "msgSchFormHandler";

module.exports = {
  SCHEDULECOMMAND,
  VIEWSCHEDULEDCOMMAND,
  SCHEDULEMESSAGEACTION,
  SCHEDULEFORMHANDLER,
};
